// Application層ユースケース: ApplyIfrsValuation
// 正常系・異常系・イベント保存失敗のテスト

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use chrono;
    use javelin_domain::{
        financial_close::closing_events::ClosingEvent,
        repositories::{MockClosingRepository, RepositoryBase},
    };

    use crate::{
        dtos::ApplyIfrsValuationRequest, input_ports::ApplyIfrsValuationUseCase,
        interactor::ApplyIfrsValuationInteractor, output_ports::ClosingOutputPort,
        query_service::LedgerQueryService,
    };

    // use the autogenerated mock from the domain layer instead of hand-rolling one
    // (`MockClosingRepository` already implements RepositoryBase< Event = ClosingEvent >)

    struct MockLedgerQueryService;
    impl LedgerQueryService for MockLedgerQueryService {
        async fn get_ledger(
            &self,
            _query: crate::query_service::ledger_query_service::GetLedgerQuery,
        ) -> crate::error::ApplicationResult<crate::query_service::ledger_query_service::LedgerResult>
        {
            Ok(crate::query_service::ledger_query_service::LedgerResult {
                account_code: "1000".to_string(),
                account_name: "Test Account".to_string(),
                opening_balance: 0.0,
                entries: vec![],
                closing_balance: 0.0,
                total_debit: 0.0,
                total_credit: 0.0,
            })
        }

        async fn get_trial_balance(
            &self,
            _query: crate::query_service::ledger_query_service::GetTrialBalanceQuery,
        ) -> crate::error::ApplicationResult<crate::query_service::TrialBalanceResult> {
            Ok(crate::query_service::TrialBalanceResult {
                period_year: 2024,
                period_month: 1,
                entries: vec![],
                total_debit: 0.0,
                total_credit: 0.0,
            })
        }
    }

    // モック ClosingOutputPort
    struct MockClosingOutputPort;
    impl ClosingOutputPort for MockClosingOutputPort {
        async fn notify_judgment_log(
            &self,
            _judgment_type: String,
            _accounting_standard: String,
            _model_used: String,
            _assumptions: Vec<String>,
            _sensitivity_analysis: Vec<String>,
            _timestamp: chrono::DateTime<chrono::Utc>,
        ) {
        }

        async fn notify_progress(&self, _message: String) {}

        async fn notify_error(&self, _error_message: String) {}
    }

    #[tokio::test]
    async fn test_successful_apply_ifrs_valuation() {
        // configure a mock repository with simple passthrough behaviour
        let mut mock_repo = MockClosingRepository::new();
        mock_repo.expect_append().returning(|_| Ok(()));
        mock_repo.expect_append_events::<ClosingEvent>().returning(|_, _| Ok(0));
        mock_repo.expect_get_events().returning(|_| Ok(vec![]));
        mock_repo.expect_get_all_events().returning(|_| Ok(vec![]));
        mock_repo.expect_get_latest_sequence().returning(|| Ok(0));
        let event_repo = Arc::new(mock_repo);
        let query_service = Arc::new(MockLedgerQueryService);
        let closing_output = Arc::new(MockClosingOutputPort);

        let interactor =
            ApplyIfrsValuationInteractor::new(event_repo, query_service, closing_output);
        let request = ApplyIfrsValuationRequest {
            fiscal_year: 2024,
            period: 12,
            user_id: "user1".to_string(),
        };
        let result = interactor.execute(request).await;
        assert!(result.is_ok());
    }
}
